---
galaxy_info:
  author: 4Linux DevOps
  description: Instalacao e Configuracao do servidor Memcached
  company: 4Linux
  license: GPLv3
  min_ansible_version: 1.2
  github_branch: homolog
  platforms:
  - name: Debian
    versions:
    - stretch
  - name: EL
    versions:
    - 7

  galaxy_tags:
  -  memcached

dependencies: []
